### ISSUE TITLE
How to install it on OS X "brew bundle ..." is not available anymore

### ISSUE THREAD

**Issue by jousch** [ctrabold/dotfiles#1]
Hi,

I've tried to install your dotfiles with homebrew. The problem is, that the "bundle" subcommand is not available anymore. Any suggestions how to install your dotfiles?

thanks in advance

**Comment by ctrabold** [comment]
oops, didn't see your issue earlier… :blush:

Usage of 'brew bundle' is described here: https://github.com/Homebrew/homebrew-bundle#install

I've removed the `bundle` feature from the `dotfiles` repo, as it was not officially supported by homebrew, then re-introduced it in https://github.com/ctrabold/workstation/blob/master/Brewfile.

Still trying to figure out how to separate `dotfiles` and application setup - or merge them, having ansible & dotfiles together?
